[package]
name = "ray-tracer"
version = "0.1.0"
authors = ["Amey Kusurkar <amey1000@gmail.com>"]
edition = "2021"

[dependencies]
rand = "0.8.5"
indicatif = "0.17.8"
image = "0.25.2"
rayon = "1.10.0"
clap = { version = "4.5.13", features = ["derive"] }

[profile.release]
debug = true
